### ISSUE TITLE
Don’t populate Bundle.entry.fullUrl

### ISSUE THREAD

**Issue by PeterGresty** [nhsconnect/gpconnect-provider-testing#220]
After discussion with suppliers, it has been decided that Bundle.entry.fullUrl shall not be populated for all our capabilities.

Added 18/04/2019 - see update below.  Providers now SHOULD NOT populate this element.  (It previously was MUST NOT).

**Comment by jonnyry** [comment]
Includes Find patient / Find organisation / Find practitioner / Search for Free Slots / Retrieve patient appointments / Get structured Record

(basically anywhere in the 1.x spec where a bundle is being returned)

Recommended test - check that the element is not present in the above calls.

**Comment by jonnyry** [comment]
Spec ticket: https://github.com/nhsconnect/gpconnect/issues/605
Demonstrator ticket: https://github.com/nhsconnect/gpconnect-demonstrator/issues/215

**Comment by jonnyry** [comment]
Following a meeting 17 Apr 2019 about 1.2.3 release scope, there has been a change to Bundle.entry.fullUrl population in order to reduce the amount of work for providers.
 
The previous spec wording was:
 
- Providers MUST NOT populate Bundle.entry.fullUrl.

 
The new spec wording is:
 
- Providers SHOULD NOT populate Bundle.entry.fullUrl.

- Consumers MUST NOT use Bundle.entry.fullUrl.

 
In terms of demonstrator and provider test suite:
 
Demonstrator – Bundle.entry.fullUrl should still be removed
Provider test suite – this requires a change to remove the tests checking for the absence of the Bundle.entry.fullUrl element
