### ISSUE TITLE
Register patient which is not on the Spine - potential change to the error text returned

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#80]
The Patient Register test 'Register patient which is not the Spine' fails because the test expects BAD_REQUEST with a status code of 400.

It's been suggested that this is not the most appropriate error and perhaps 'INVALID_PATIENT_DEMOGRAPHICS' would be better (with a status code of 400)

Please can you advise.

**Comment by jonnyry** [comment]
As agreed with @jackiebarnes, @AndrewGuiseley & @RiChallinor - 

Agree this error is incorrect and should be INVALID_PATIENT_DEMOGRAPHICS.

Since this could be classed as a "business error" (rather than a "technical error") where a consumer may want to present a specific message to a consumer based on this specific error happening (rather than simply putting the error in the log and failing), the test suite should be changed to correct this.

Could you also check other automated tests for Register Patient and check whether there's any others that should be INVALID_PATIENT_DEMOGRAPHICS and are currently set to something else?

**Comment by AndrewGuiseley** [comment]
Checked the rest of the RegisterPatient tests and as far as l can see this change needs only to be made to the one test ('Register patient which is not the Spine')

**Comment by rbutterf** [comment]
Amended Test suite ... demonstrator needs changing
