### ISSUE TITLE
Structured test suite - Coding System extension

### ISSUE THREAD

**Issue by AndrewGuiseley** [nhsconnect/gpconnect-provider-testing#85]
Clarification needed on what should be expected to be returned from each coding system.

In AccessStructuredMedicationSteps.cs, in the method TheMedicationCodeShouldBeValid, the test is expecting every coding system to be “http://snomed.info/sct” and have a description Id extension present. EMIS are passing an EMIS drug code with SNOMED translation

**Comment by PeteSalis** [comment]
Email sent to team this am

All

For New 1 the SNOMED DeccriptionID extension in the code element is optional so does not always need to be populated. Where a code was input in a legacy system and translated to SNOMED they are usually translated to a ConceptID and will not have a DescriptionID.

In this case it has been translated to a ConceptID and they have added in the preferred term to the display. This should also not be populated which is why the display element has also been defined as optional. So the example they have given should look like this,

"code": {
          "coding": [
            {
              "system": "https://fhir.hl7.org.uk/Id/emis-drug-codes",
              "code": "SUCR2721",
              "display": "Sudocrem antiseptic healing cream (Teva UK Ltd)",
              "userSelected": true
            },
            {
              "system": "http://snomed.info/sct",
              "code": "804511000001102"
            }
          ]
        }

Regards

Pete

**Comment by jonnyry** [comment]
Instead of just testing for http://snomed.info/sct, the list should be expanded to test for the any appropriate code systems from the list at:

https://nhsconnect.github.io/gpconnect/accessrecord_structured_development_resources_overview.html#common-code-systems

**Comment by rbutterf** [comment]
amended test suite to check coding is one of 
	SNOMED CT http://snomed.info/sct 
	Read codes V2 http://read.info/readv2 
	Read codes CTV3 http://read.info/ctv3 
	EMIS drug codes https://fhir.hl7.org.uk/Id/emis-drug-codes 
	Egton codes https://fhir.hl7.org.uk/Id/egton-codes 
	Multilex drug codes https://fhir.hl7.org.uk/Id/multilex-drug-codes 
	Resip UK Gemscript drug codes https://fhir.hl7.org.uk/Id/resipuk-gemscript-drug-codes
